[package]
name = "actuator"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
chrono-tz = { version = "0.10.0", features = ["case-insensitive"] }
rppal = "0.19.0"
thiserror = "2.0.3"
